### ISSUE TITLE
visualizing the calm trained model

### ISSUE THREAD

**Issue by lizeyujack** [naver-ai/calm#1]
Hello,
I am very interested in your work. Could you give me some tips about how to visualize the data into heatmap form?

Thanks.
Zeyu Li

**Comment by goldkim92** [comment]
Hi @lizeyujack,

Thank you for having an interest in our work. 
Similar to CAM, we get the intermediate feature maps F \in R^{C x H x W} (Orange box in Fig. 2(c)), and take a slice of F on the target class, F[c] \in R^{H x W}, to get the final attribution map. You can directly visualize the attribution map since each attribution in the attribution map is the probability value, having in the range of [0,1].

**Comment by lizeyujack** [comment]
> Hi @lizeyujack,
> 
> Thank you for having an interest in our work. Similar to CAM, we get the intermediate feature maps F \in R^{C x H x W} (Orange box in Fig. 2(c)), and take a slice of F on the target class, F[c] \in R^{H x W}, to get the final attribution map. You can directly visualize the attribution map since each attribution in the attribution map is the probability value, having in the range of [0,1].

Thanks for getting reply from. Your tips is really helpful for me.
